package com.pojos;
// Generated Nov 5, 2020 4:54:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
    ,catalog="importadorapoe"
)
public class Categoria  implements java.io.Serializable {


     private int idCategoria;
     private String nombreCategoria;
     private Set<Vehiculo> vehiculos = new HashSet<Vehiculo>(0);

    public Categoria() {
    }

	
    public Categoria(int idCategoria, String nombreCategoria) {
        this.idCategoria = idCategoria;
        this.nombreCategoria = nombreCategoria;
    }
    public Categoria(int idCategoria, String nombreCategoria, Set<Vehiculo> vehiculos) {
       this.idCategoria = idCategoria;
       this.nombreCategoria = nombreCategoria;
       this.vehiculos = vehiculos;
    }
   
     @Id 

    
    @Column(name="id_categoria", unique=true, nullable=false)
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="nombre_categoria", nullable=false, length=200)
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set<Vehiculo> getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set<Vehiculo> vehiculos) {
        this.vehiculos = vehiculos;
    }




}


