package com.pojos;
// Generated Nov 19, 2020 10:51:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="importadorapoe"
)
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private Usuario usuario;
     private String nombreCliente;
     private String telefonoCliente;
     private String direccionCliente;

    public Cliente() {
    }

    public Cliente(Usuario usuario, String nombreCliente, String telefonoCliente, String direccionCliente) {
       this.usuario = usuario;
       this.nombreCliente = nombreCliente;
       this.telefonoCliente = telefonoCliente;
       this.direccionCliente = direccionCliente;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cliente", unique=true, nullable=false)
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre_cliente", nullable=false, length=200)
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }

    
    @Column(name="telefono_cliente", nullable=false, length=20)
    public String getTelefonoCliente() {
        return this.telefonoCliente;
    }
    
    public void setTelefonoCliente(String telefonoCliente) {
        this.telefonoCliente = telefonoCliente;
    }

    
    @Column(name="direccion_cliente", nullable=false, length=200)
    public String getDireccionCliente() {
        return this.direccionCliente;
    }
    
    public void setDireccionCliente(String direccionCliente) {
        this.direccionCliente = direccionCliente;
    }




}


