package com.pojos;
// Generated Nov 19, 2020 10:51:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleOferta generated by hbm2java
 */
@Entity
@Table(name="detalle_oferta"
    ,catalog="importadorapoe"
)
public class DetalleOferta  implements java.io.Serializable {


     private DetalleOfertaId id;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private int cantidad;
     private Date fechaOferta;

    public DetalleOferta() {
    }

	
    public DetalleOferta(DetalleOfertaId id, Usuario usuario, Vehiculo vehiculo, int cantidad) {
        this.id = id;
        this.usuario = usuario;
        this.vehiculo = vehiculo;
        this.cantidad = cantidad;
    }
    public DetalleOferta(DetalleOfertaId id, Usuario usuario, Vehiculo vehiculo, int cantidad, Date fechaOferta) {
       this.id = id;
       this.usuario = usuario;
       this.vehiculo = vehiculo;
       this.cantidad = cantidad;
       this.fechaOferta = fechaOferta;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idDetalle", column=@Column(name="id_detalle", nullable=false) ), 
        @AttributeOverride(name="idVehiculo", column=@Column(name="id_vehiculo", nullable=false) ) } )
    public DetalleOfertaId getId() {
        return this.id;
    }
    
    public void setId(DetalleOfertaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vehiculo", nullable=false, insertable=false, updatable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_oferta", length=10)
    public Date getFechaOferta() {
        return this.fechaOferta;
    }
    
    public void setFechaOferta(Date fechaOferta) {
        this.fechaOferta = fechaOferta;
    }




}


