package com.pojos;
// Generated Nov 5, 2020 4:54:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleOferta generated by hbm2java
 */
@Entity
@Table(name="detalle_oferta"
    ,catalog="importadorapoe"
)
public class DetalleOferta  implements java.io.Serializable {


     private int idDetalle;
     private Impuesto impuesto;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private Float totalCompra;
     private Float totalImpuesto;
     private int cantidad;
     private Date fechaOferta;

    public DetalleOferta() {
    }

	
    public DetalleOferta(int idDetalle, Impuesto impuesto, Usuario usuario, Vehiculo vehiculo, int cantidad) {
        this.idDetalle = idDetalle;
        this.impuesto = impuesto;
        this.usuario = usuario;
        this.vehiculo = vehiculo;
        this.cantidad = cantidad;
    }
    public DetalleOferta(int idDetalle, Impuesto impuesto, Usuario usuario, Vehiculo vehiculo, Float totalCompra, Float totalImpuesto, int cantidad, Date fechaOferta) {
       this.idDetalle = idDetalle;
       this.impuesto = impuesto;
       this.usuario = usuario;
       this.vehiculo = vehiculo;
       this.totalCompra = totalCompra;
       this.totalImpuesto = totalImpuesto;
       this.cantidad = cantidad;
       this.fechaOferta = fechaOferta;
    }
   
     @Id 

    
    @Column(name="id_detalle", unique=true, nullable=false)
    public int getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_impuesto", nullable=false)
    public Impuesto getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(Impuesto impuesto) {
        this.impuesto = impuesto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vehiculo", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="total_compra", precision=12, scale=0)
    public Float getTotalCompra() {
        return this.totalCompra;
    }
    
    public void setTotalCompra(Float totalCompra) {
        this.totalCompra = totalCompra;
    }

    
    @Column(name="total_impuesto", precision=12, scale=0)
    public Float getTotalImpuesto() {
        return this.totalImpuesto;
    }
    
    public void setTotalImpuesto(Float totalImpuesto) {
        this.totalImpuesto = totalImpuesto;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_oferta", length=10)
    public Date getFechaOferta() {
        return this.fechaOferta;
    }
    
    public void setFechaOferta(Date fechaOferta) {
        this.fechaOferta = fechaOferta;
    }




}


