package com.pojos;
// Generated Nov 19, 2020 10:51:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetalleOfertaId generated by hbm2java
 */
@Embeddable
public class DetalleOfertaId  implements java.io.Serializable {


     private int idDetalle;
     private int idVehiculo;

    public DetalleOfertaId() {
    }

    public DetalleOfertaId(int idDetalle, int idVehiculo) {
       this.idDetalle = idDetalle;
       this.idVehiculo = idVehiculo;
    }
   


    @Column(name="id_detalle", nullable=false)
    public int getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }


    @Column(name="id_vehiculo", nullable=false)
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleOfertaId) ) return false;
		 DetalleOfertaId castOther = ( DetalleOfertaId ) other; 
         
		 return (this.getIdDetalle()==castOther.getIdDetalle())
 && (this.getIdVehiculo()==castOther.getIdVehiculo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDetalle();
         result = 37 * result + this.getIdVehiculo();
         return result;
   }   


}


