package com.pojos;
// Generated Nov 5, 2020 4:54:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Impuesto generated by hbm2java
 */
@Entity
@Table(name="impuesto"
    ,catalog="importadorapoe"
)
public class Impuesto  implements java.io.Serializable {


     private int idImpuesto;
     private String nombre;
     private Float valor;
     private Set<DetalleOferta> detalleOfertas = new HashSet<DetalleOferta>(0);

    public Impuesto() {
    }

	
    public Impuesto(int idImpuesto, String nombre) {
        this.idImpuesto = idImpuesto;
        this.nombre = nombre;
    }
    public Impuesto(int idImpuesto, String nombre, Float valor, Set<DetalleOferta> detalleOfertas) {
       this.idImpuesto = idImpuesto;
       this.nombre = nombre;
       this.valor = valor;
       this.detalleOfertas = detalleOfertas;
    }
   
     @Id 

    
    @Column(name="id_impuesto", unique=true, nullable=false)
    public int getIdImpuesto() {
        return this.idImpuesto;
    }
    
    public void setIdImpuesto(int idImpuesto) {
        this.idImpuesto = idImpuesto;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="valor", precision=12, scale=0)
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="impuesto")
    public Set<DetalleOferta> getDetalleOfertas() {
        return this.detalleOfertas;
    }
    
    public void setDetalleOfertas(Set<DetalleOferta> detalleOfertas) {
        this.detalleOfertas = detalleOfertas;
    }




}


