package com.pojos;
// Generated Nov 19, 2020 10:51:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor"
    ,catalog="importadorapoe"
)
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private Usuario usuario;
     private String nombreProveedor;
     private String direccionProveedor;
     private String telefonoProveedor;

    public Proveedor() {
    }

    public Proveedor(Usuario usuario, String nombreProveedor, String direccionProveedor, String telefonoProveedor) {
       this.usuario = usuario;
       this.nombreProveedor = nombreProveedor;
       this.direccionProveedor = direccionProveedor;
       this.telefonoProveedor = telefonoProveedor;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_proveedor", unique=true, nullable=false)
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre_proveedor", nullable=false, length=200)
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }

    
    @Column(name="direccion_proveedor", nullable=false, length=200)
    public String getDireccionProveedor() {
        return this.direccionProveedor;
    }
    
    public void setDireccionProveedor(String direccionProveedor) {
        this.direccionProveedor = direccionProveedor;
    }

    
    @Column(name="telefono_proveedor", nullable=false, length=20)
    public String getTelefonoProveedor() {
        return this.telefonoProveedor;
    }
    
    public void setTelefonoProveedor(String telefonoProveedor) {
        this.telefonoProveedor = telefonoProveedor;
    }




}


