package com.pojos;
// Generated Nov 10, 2020 5:30:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="importadorapoe"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombreUsuario;
     private String correoUsuario;
     private String contra;
     private int tipoUsuario;
     private String foto;
     private Set<DetalleOferta> detalleOfertas = new HashSet<DetalleOferta>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);

    public Usuario() {
    }
    
    public Usuario(int id){
        this.idUsuario = id;
    }

	
    public Usuario(String nombreUsuario, String correoUsuario, String contra, int tipoUsuario, String foto) {
        this.nombreUsuario = nombreUsuario;
        this.correoUsuario = correoUsuario;
        this.contra = contra;
        this.tipoUsuario = tipoUsuario;
        this.foto = foto;
    }
    public Usuario(String nombreUsuario, String correoUsuario, String contra, int tipoUsuario, String foto, Set<DetalleOferta> detalleOfertas, Set<Cliente> clientes, Set<Proveedor> proveedors) {
       this.nombreUsuario = nombreUsuario;
       this.correoUsuario = correoUsuario;
       this.contra = contra;
       this.tipoUsuario = tipoUsuario;
       this.foto = foto;
       this.detalleOfertas = detalleOfertas;
       this.clientes = clientes;
       this.proveedors = proveedors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nombre_usuario", nullable=false, length=200)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="correo_usuario", nullable=false, length=200)
    public String getCorreoUsuario() {
        return this.correoUsuario;
    }
    
    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }

    
    @Column(name="contra", nullable=false, length=11)
    public String getContra() {
        return this.contra;
    }
    
    public void setContra(String contra) {
        this.contra = contra;
    }

    
    @Column(name="tipo_usuario", nullable=false)
    public int getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(int tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    
    @Column(name="foto", nullable=false, length=150)
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<DetalleOferta> getDetalleOfertas() {
        return this.detalleOfertas;
    }
    
    public void setDetalleOfertas(Set<DetalleOferta> detalleOfertas) {
        this.detalleOfertas = detalleOfertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }




}


